//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devshed.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devshed.Web.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compared value does not match value..
        /// </summary>
        internal static string ComparedControlValuesDontMatch {
            get {
                return ResourceManager.GetString("ComparedControlValuesDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compared value does not match field..
        /// </summary>
        internal static string ComparedValueDontMatchField {
            get {
                return ResourceManager.GetString("ComparedValueDontMatchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be erlier than field &apos;{0}&apos;..
        /// </summary>
        internal static string DateControlMustBeEarlierOrEqual {
            get {
                return ResourceManager.GetString("DateControlMustBeEarlierOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be earlier or equal to &apos;{0}&apos;..
        /// </summary>
        internal static string DateMustBeEarlierOrEqual {
            get {
                return ResourceManager.GetString("DateMustBeEarlierOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be earlier than &apos;{0}&apos;..
        /// </summary>
        internal static string DateMustBeEarlierThan {
            get {
                return ResourceManager.GetString("DateMustBeEarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be later or equal to {0}..
        /// </summary>
        internal static string DateMustBeLaterOrEqual {
            get {
                return ResourceManager.GetString("DateMustBeLaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be later than &apos;{0}&apos;..
        /// </summary>
        internal static string DateMustBeLaterThan {
            get {
                return ResourceManager.GetString("DateMustBeLaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email formatting is not valid..
        /// </summary>
        internal static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of field is exceeded..
        /// </summary>
        internal static string MaximumStringLengthExceeded {
            get {
                return ResourceManager.GetString("MaximumStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must greater or equal to {0}..
        /// </summary>
        internal static string NumberMustBeHigherOrEqualTo {
            get {
                return ResourceManager.GetString("NumberMustBeHigherOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must greater than {0}..
        /// </summary>
        internal static string NumberMustBeHigherThan {
            get {
                return ResourceManager.GetString("NumberMustBeHigherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less or equal to {0}..
        /// </summary>
        internal static string NumberMustBeLessOrEqualTo {
            get {
                return ResourceManager.GetString("NumberMustBeLessOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than {0}..
        /// </summary>
        internal static string NumberMustBeLessThan {
            get {
                return ResourceManager.GetString("NumberMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet requirements..
        /// </summary>
        internal static string PasswordDoesNotMatchRequirements {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatchRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is required..
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time formatting is not valid..
        /// </summary>
        internal static string TimeFormatInvalid {
            get {
                return ResourceManager.GetString("TimeFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url formatting is invalid..
        /// </summary>
        internal static string UrlIsNotValid {
            get {
                return ResourceManager.GetString("UrlIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must of type &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBeOfType {
            get {
                return ResourceManager.GetString("ValueMustBeOfType", resourceCulture);
            }
        }
    }
}
